Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  # APT cacher VM
  config.vm.define "apt-cacher" do |apt_cacher|
    apt_cacher.vm.network "public_network", type:"dhcp"
    apt_cacher.vm.hostname = "apt-cacher"
    apt_cacher.vm.provision "shell", path:"setup_apt_cacher.sh"
  end

  # client 1
  config.vm.define "client-1" do |client_1|
    client_1.vm.network "public_network", type:"dhcp"
    client_1.vm.hostname = "client-1"
    client_1.vm.provision "shell", path:"setup_client.sh"
  end

  # client 2 
  config.vm.define "client-2" do |client_2|
    client_2.vm.network "public_network", type:"dhcp"
    client_2.vm.hostname = "client-2"
    client_2.vm.provision "shell", path:"setup_client.sh"
  end
end
