# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "private_network", type: "dhcp"
  config.dns.ip = -> (vm, opts) do
    # note: the block handed to `execute` might get called multiple times, hence this closure
    ip = nil
    vm.communicate.execute("hostname -I | cut -d ' ' -f 2") do |type, data|
      ip = data.strip if type == :stdout
    end
    ip
  end
  config.dns.tld = "domain"
  
  config.vm.define "harbor" do |harbor|
    harbor.vm.provision :shell, path: "install_harbor.sh"
    harbor.vm.hostname = "harbor"
  end
  
  config.vm.define "ca" do |ca|
    ca.vm.provision :shell, path: "install_stepca.sh"
    ca.vm.hostname = "ca"
  end
end

VagrantDNS::Config.passthrough = false
