Vagrant.configure("2") do |config|
  config.vm.provider "vmware_fusion"

  config.vm.box = "bento/ubuntu-20.04-arm64"

  # APT cacher VM
  config.vm.define "apt-cacher" do |apt_cacher|
    apt_cacher.vm.provider "vmware_fusion" do |v|
      #number of virtual CPUs
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "512"
    end
    apt_cacher.vm.network "private_network"
    apt_cacher.vm.network "forwarded_port", guest: 3142, host: 3142
    apt_cacher.vm.hostname = "apt-cacher"
    apt_cacher.vm.provision "shell", path:"setup_apt_cacher.sh"
    # setup a shared folder for configuration file
    apt_cacher.vm.synced_folder "config/", "/vagrant/config"
  end

  # client 1
  config.vm.define "client-1" do |client_1|
    client_1.vm.provider "vmware_fusion" do |v|
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "2048"
    end
    client_1.vm.network "private_network"
    client_1.vm.hostname = "client-1"
    client_1.vm.provision "shell", path:"setup_client.sh"
    client_1.vm.synced_folder "config/", "/vagrant/config"
  end

  # client 2 
  config.vm.define "client-2" do |client_2|
    client_2.vm.provider "vmware_fusion" do |v|
      v.vmx["numvcpus"] = "2"
      v.vmx["memsize"] = "2048"
    end
    client_2.vm.network "private_network" 
    client_2.vm.hostname = "client-2"
    client_2.vm.provision "shell", path:"setup_client.sh"
    client_2.vm.synced_folder "config/", "/vagrant/config"
  end
end








